<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.2.1</Version>
  </PropertyGroup>
  
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>HungarianNotation.PseudoDrop</RootNamespace>
    <AssemblyName>HungarianNotation.PseudoDrop</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Package\CHANGELOG.md" />
    <None Remove="Package\README.md" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
    <None Include="README.md" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="JotunnLib" Version="2.30.2" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <PropertyGroup>
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>true</TransformOutOfDateOnly>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Package\manifest.json">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>manifest.tt</DependentUpon>
    </None>
    <None Update="Package\manifest.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>manifest.json</LastGenOutput>
    </None>
    <None Update="Plugin_Version.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Plugin_Version.cs</LastGenOutput>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Plugin_Version.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Plugin_Version.tt</DependentUpon>
    </Compile>
  </ItemGroup>  

  <PropertyGroup>
    <VALHEIM_MANAGED>$(VALHEIM_INSTALL)/valheim_Data/Managed</VALHEIM_MANAGED>
    <UNITY_FOLDER>$(SolutionDir)JotunnModStubUnity</UNITY_FOLDER>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
  </PropertyGroup>
  
  <Target Name="JotunnPostBuildTaskWin" AfterTargets="Build" Condition=" '$(OS)' == 'Windows_NT' ">
    <Exec Command="powershell.exe -ExecutionPolicy RemoteSigned -File &quot;$(SolutionDir)scripts/publish.ps1&quot; -Target &quot;$(ConfigurationName)&quot; -TargetPath &quot;$(TargetDir.TrimEnd('\'))&quot; -TargetAssembly &quot;$(TargetFileName)&quot; -ValheimPath &quot;$(VALHEIM_INSTALL.TrimEnd('\'))&quot; -DeployPath &quot;$(MOD_DEPLOYPATH.TrimEnd('\'))&quot; -ProjectPath &quot;$(ProjectDir.TrimEnd('\'))&quot; " />
  </Target>

</Project>